trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  displayName: Build and push Docker image
  inputs:
    containerRegistry: 'Docker-Service-Connection-amaruf1'
    repository: 'amaruf1/web-app-devops-project'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'v1.0'